-- MySQL Script generated by MySQL Workbench
-- Tue Jan  3 22:04:23 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema technolife
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tecnolife
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tecnolife` ;

-- -----------------------------------------------------
-- Schema tecnolife
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tecnolife` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `tecnolife` ;

-- -----------------------------------------------------
-- Table `tecnolife`.`banners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecnolife`.`banners` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_imagen` VARCHAR(100) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tecnolife`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecnolife`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tecnolife`.`marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecnolife`.`marcas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tecnolife`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecnolife`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `stock` INT NOT NULL,
  `precio` INT NOT NULL,
  `descuento` INT NOT NULL,
  `descripcion` VARCHAR(400) NOT NULL,
  `categorias_id` INT NOT NULL,
  `marcas_id` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `productos_ibfk_1`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `tecnolife`.`categorias` (`id`),
  CONSTRAINT `productos_ibfk_2`
    FOREIGN KEY (`marcas_id`)
    REFERENCES `tecnolife`.`marcas` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `categorias_id` ON `tecnolife`.`productos` (`categorias_id` ASC) VISIBLE;

CREATE INDEX `marcas_id` ON `tecnolife`.`productos` (`marcas_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tecnolife`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecnolife`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `genero` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(250) NOT NULL,
  `ciudad` VARCHAR(100) NOT NULL,
  `imagen` VARCHAR(100) NOT NULL,
  `rol` VARCHAR(100) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tecnolife`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecnolife`.`carrito` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `productos_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `carrito_ibfk_1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `tecnolife`.`productos` (`id`),
  CONSTRAINT `carrito_ibfk_2`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `tecnolife`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `productos_id` ON `tecnolife`.`carrito` (`productos_id` ASC) VISIBLE;

CREATE INDEX `usuarios_id` ON `tecnolife`.`carrito` (`usuarios_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tecnolife`.`imagenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecnolife`.`imagenes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `productos_id` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `imagenes_ibfk_1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `tecnolife`.`productos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `productos_id` ON `tecnolife`.`imagenes` (`productos_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tecnolife`.`ordenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecnolife`.`ordenes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `carritos_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `ordenes_ibfk_1`
    FOREIGN KEY (`carritos_id`)
    REFERENCES `tecnolife`.`usuarios` (`id`),
  CONSTRAINT `ordenes_ibfk_2`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `tecnolife`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `carritos_id` ON `tecnolife`.`ordenes` (`carritos_id` ASC) VISIBLE;

CREATE INDEX `usuarios_id` ON `tecnolife`.`ordenes` (`usuarios_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `tecnolife`.`sequelizemeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecnolife`.`sequelizemeta` (
  `name` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name` ON `tecnolife`.`sequelizemeta` (`name` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
